version: "3.3"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  database:
  website:

services:

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - database
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOTPASSWORD: ${MYSQL_ROOTPASSWORD}

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress:/var/www/inception
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - website
      - database
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_ADDRESS: ${WP_ADDRESS}
      WP_TITLE: ${WP_TITLE}

  nginx:
    build: requirements/nginx/
    container_name: nginx
    volumes:
      - wordpress:/var/www/inception
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - website
    restart: always

  ftp:
    build: requirements/ftp_bonus/
    container_name: ftp
    volumes:
      - wordpress:/var/www/inception
    ports:
      - "20:20"
      - "21:21"
      - "40000-40009:40000-40009"
    depends_on:
      - wordpress
    networks:
      - website
    restart: always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
      FTP_GROUP: ${FTP_GROUP}

  redis:
    build: requirements/redis_bonus/
    container_name: redis
    volums:
      - wordpress:/var/www/inception
    depends_on:
      - wordpress
    networks:
      - website
    restart: always
